version: "3.5"

networks:
  internet:
    name: internet
    driver: bridge
  
  appnet:
    name: appnet
    driver: bridge

services:
  web:
    container_name: web
    image: lukesv/guess-number-game-web
    networks:
    - internet
    - appnet
    ports:
    - "8081:80"
    restart: unless-stopped
    depends_on:
    - player-service

  player-service:
    container_name: player-service
    image: lukesv/guess-number-game-player-service
    networks:
    - appnet
    ports:
    - "8082:80"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_SCHEMA: guess_number_game
    restart: unless-stopped
    depends_on:
    - postgres

  postgres:
    container_name: postgres
    image: postgres::alpine3.18
    networks:
    - appnet
    environment:
      POSTGRES_DATABASE: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    restart: unless-stopped
